{% set version = "2.0.1" %}

package:
  name: cc-plugin-ncei
  version: {{ version }}

source:
  fn: cc-plugin-ncei-{{ version }}.tar.gz
  url: https://github.com/ioos/cc-plugin-ncei/archive/{{ version }}.tar.gz
  sha256: 420cbc9dbf0e28c454a97ab127dad1d5de377efdc0d48b29908628fa0a981516

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - compliance-checker >=1.0.0
    - isodate

test:
  imports:
    - cc_plugin_ncei
    - cc_plugin_ncei.tests
  commands:
    - compliance-checker -t ncei-trajectory-profile-orthogonal -v https://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectoryProfile_template_v1.1_2016-06-15_133721.704494.nc

about:
  home: https://github.com/ioos/cc-plugin-ncei/
  license: Apache 2.0
  summary: 'Compliance Checker NCEI Templates Compliance plugin.'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
