# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WZ3yrX4ABaZFyMYlqzzfKuIsP+k4qGHbjTMgzSY83A74BtCaNB+zyy1pXRWCEEda20pt6r+emp62S1bJrl8ZZTyHfDE2rvuhs/pNOkYSx8bS3zPGquX8mLcPH7yIsL20UV1/sWIs8CRIQos4eFUhl5PFqY1JtjOGRyeAD8wfdEdxSltwbWnJ7GoafBwHsO1r4ull/nV4HPksNXoCuaNBYhcNYavBmqURn8Z+ERLGgela59EAFi0YJ3siGZMzQ5BuWkzNl+fZzujL4ePJuz6FDrpVji5cdReM0mXnH9SS0StblzkOAJ3K/PX9JzLYSX88kJf1eDBrm257kcYZWFtKqamFVoajHGq5WDgw4mCQ1M2XXVmKcPXAyDTOHZfgT3ilihvvxB8+D2W8hjNobeocLYhXpt20Jdaqh7cmauCvxbRNllSTy3vGerd7+pIbFbyXcrtOlDY4tDS1IVW01QQv259jieiSUKJrspJXurCTiCUMofPkQ6MTIFBM6WU/LQI2VciMdR7hvdiL8hdoDhdwb8oAXrAB6btrtcg1epMLGX8eSYAYDuNcOB9nQ93y9d8WZRGxjqxEkgHSAP5lyoFSvAmnBSmsLmEb3O4T/RBgGhDUslbSKNVOcD4sWeYhXsAP4tDktTqU1DOt6udmUUt8E8IXESfw+cFc9tgahpV8y+k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
