travis:
  secure:
    BINSTAR_TOKEN: WZ3yrX4ABaZFyMYlqzzfKuIsP+k4qGHbjTMgzSY83A74BtCaNB+zyy1pXRWCEEda20pt6r+emp62S1bJrl8ZZTyHfDE2rvuhs/pNOkYSx8bS3zPGquX8mLcPH7yIsL20UV1/sWIs8CRIQos4eFUhl5PFqY1JtjOGRyeAD8wfdEdxSltwbWnJ7GoafBwHsO1r4ull/nV4HPksNXoCuaNBYhcNYavBmqURn8Z+ERLGgela59EAFi0YJ3siGZMzQ5BuWkzNl+fZzujL4ePJuz6FDrpVji5cdReM0mXnH9SS0StblzkOAJ3K/PX9JzLYSX88kJf1eDBrm257kcYZWFtKqamFVoajHGq5WDgw4mCQ1M2XXVmKcPXAyDTOHZfgT3ilihvvxB8+D2W8hjNobeocLYhXpt20Jdaqh7cmauCvxbRNllSTy3vGerd7+pIbFbyXcrtOlDY4tDS1IVW01QQv259jieiSUKJrspJXurCTiCUMofPkQ6MTIFBM6WU/LQI2VciMdR7hvdiL8hdoDhdwb8oAXrAB6btrtcg1epMLGX8eSYAYDuNcOB9nQ93y9d8WZRGxjqxEkgHSAP5lyoFSvAmnBSmsLmEb3O4T/RBgGhDUslbSKNVOcD4sWeYhXsAP4tDktTqU1DOt6udmUUt8E8IXESfw+cFc9tgahpV8y+k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
