travis:
  secure:
    BINSTAR_TOKEN: nLMEaTtYs/ENE7olSXv6M9IfBq7aRWTkr5IaExSLScWbA2va0M5REsNstgNpCW6eGNpwowfvCXHHMZN/blHbiq7X4kxZ6aLBtiJvJeLzdFh6Id6iQuc35rfEJhX3gRVLTn41B8cj5PBZXmkcKQIahWZlkmCynYvPcwVGh8KqnrRAzULtgaMHo9wo4m8dTU5Nye5z7qi+tRVZ5eKFy+59E9/S038wmjBjkn2aZw6lLCS+zUgpdBQhs9US79v0qBH9ULZ/U9hv3RUOI941vSdyqnf9qD3p2T2yA80NhFsS1xlWv8SLEave2gy3BInlqh3QElT40rzhUMiQYkBEWRWebevtj/Bn+wXtqaieqZNf3yCKitW4qdrYghQoeo0H/ha5VoYHhe/pcUEj5RDjiZkRBBpO3pe1cw4LSxY2KJ9yd/izqPM6N0kSd1K7w7QyX2bKzp/7SozaqsocqtYKs5MBH8QSvpwM4m0qG6qeX+LqPqChfQo3egSV0PkpTFrq0sFRGBWRpg3JhioxTQLp+Zvmx5r0YsQoFwRKsQicS531YzPMZYoq9/Iec2sJIKv06WZp7KCG0FJtzaleO/jFxSsqzIm3KvbIbSgWX4r37CtKwjTFjUYz5W2OId1tBvm5HI7lw1wEtignGaz7nLkIGn9i9gFJEGh3RKkqLuxWfc9BrxE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
